---

- ansible.builtin.include_tasks: ../common/check_installed_package.yml
  vars:
    package: telnet
    present: no
    description: Ensure telnet client is not installed
  name: >-
    Perform check {{ cis_audit_item }} / {{ description }}
  no_log: "{{ cis_no_log }}"
