---

- include_tasks: ../common/check_param.yml
  vars:
    description: Ensure SSH Idle Timeout Interval is configured
    file: /etc/ssh/sshd_config
    parameter: ClientAliveInterval
    # delimiter: ' '
    value: 1
    value_type: int
    comparison: ">="
  name: "Check {{ parameter }}{{ comparison }}{{ value }} in {{ file }}"
  no_log: "{{ cis_no_log }}"

- include_tasks: ../common/check_param.yml
  # Chaining checks
  when: not cis_check_result is failed
  vars:
    description: Ensure SSH Idle Timeout Interval is configured
    file: /etc/ssh/sshd_config
    parameter: ClientAliveInterval
    value: 300
    value_type: int
    comparison: "<="
  name: "Check {{ parameter }}{{ comparison }}{{ value }} in {{ file }}"
  no_log: "{{ cis_no_log }}"

- include_tasks: ../common/check_param.yml
  when: not cis_check_result is failed
  vars:
    description: Ensure SSH Idle Timeout Interval is configured
    file: /etc/ssh/sshd_config
    parameter: ClientAliveCountMax
    value: 3
    value_type: int
    comparison: "<="
  name: "Check {{ parameter }}{{ comparison }}{{ value }} in {{ file }}"
  no_log: "{{ cis_no_log }}"
