---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure SSH IgnoreRhosts is enabled

- name: "{{ cis_check_description }}"
  vars:
    pattern: "^HostbasedAuthentication\s+no"
    grep_result: >-
      {{ cis_sshd_config
      | map('regex_search', pattern)
      | select('string')
      | list }}
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: grep_result | length > 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
