---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: >-
      Ensure auditing for processes that start prior to auditd is enabled

- name: >-
    Gather data to ensure auditing for processes that start prior to auditd is
    enabled
  ansible.builtin.command: grep "linux[0-9]* /" /boot/grub2/grub.cfg
  changed_when: no
  failed_when: no
  register: cis_gather_data_grub_result

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      cis_gather_data_grub_result.stdout_lines
      | select("search", "audit=1")
      | list
      | length == cis_gather_data_grub_result.stdout_lines | length
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
