---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure X Window System is not installed

- name: Gather data to ensure X Window System is not installed
  yum:
    name: xorg-x11*
    state: absent
  register: cis_x_check_result
  check_mode: yes
  changed_when: no
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_x_check_result is not changed
      - cis_x_check_result is success
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
