---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure AIDE is installed

- name: Gather data to to ensure prelink is disabled
  yum:
    name: aide
    state: present
  register: cis_aide_check_result
  check_mode: yes
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_aide_check_result is not changed
      - cis_aide_check_result is success
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
