---

- name: Ensure secure ICMP redirects are not accepted
  assert:
    that:
      - ("net.ipv4.conf.all.secure_redirects = 0" in cis_kernel_params)
      - ("net.ipv4.conf.default.secure_redirects = 0" in cis_kernel_params)
  register: cis_check_result
