---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: >-
      Ensure events that modify the system's Mandatory Access Controls are
      collected

- name: Gather data from audit.rules and /etc/audit/rules.d/*.rules
  ansible.builtin.shell: >-
    grep --no-filename MAC-policy
    /etc/audit/audit.rules /etc/audit/rules.d/*.rules
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_audit_rules_result

- name: "{{ cis_check_description }}"
  vars:
    desired_output:
      - "-w /etc/selinux/ -p wa -k MAC-policy"
      - "-w /usr/share/selinux/ -p wa -k MAC-policy"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_audit_rules_result.stdout | length > 0
      - >-
        desired_output
        is subset(cis_gather_data_audit_rules_result.stdout_lines)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
