---

- include_tasks: ../common/check_sshd.yml
  vars:
    description: Ensure SSH X11 forwarding is disabled
    value: x11forwarding no
  name: "Perform sshd config contains: {{ value }}"
  no_log: "{{ cis_no_log }}"
