---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure packet redirect sending is disabled

- name: >-
    Gather data to ensure packet redirect sending is disabled - all -
    /etc/sysctl**
  command: >-
    /usr/bin/grep "net\.ipv4\.conf\.all\.send_redirects"
    /etc/sysctl.conf /etc/sysctl.d/*
  changed_when: no
  failed_when: no
  register: cis_gather_data_etc_sysctl_all_result

- name: >-
    Gather data to ensure packet redirect sending is disabled - default -
    /etc/sysctl**
  command: >-
    /usr/bin/grep "net\.ipv4\.conf\.default\.send_redirects"
    /etc/sysctl.conf /etc/sysctl.d/*
  changed_when: no
  failed_when: no
  register: cis_gather_data_etc_sysctl_default_result

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - ("net.ipv4.conf.all.send_redirects = 0" in cis_kernel_params)
      - ("net.ipv4.conf.default.send_redirects = 0" in cis_kernel_params)
      - "cis_gather_data_etc_sysctl_all_result | length > 0"
      - "cis_gather_data_etc_sysctl_default_result | length > 0"
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
