---

- include_tasks: ../common/check_installed_package.yml
  vars:
    package: openldap-clients
    present: no
    description: Ensure LDAP client is not installed
  name: >-
    Perform check {{ cis_audit_item }} / {{ description }}
  no_log: "{{ cis_no_log }}"
