---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure core dumps are restricted

- name: Gather data to ensure core dumps are restricted - limits
  command: >-
    /usr/bin/grep \
    '^[^#]*hard core' /etc/security/limits.conf /etc/security/limits.d/*
  become: yes
  changed_when: false
  register: cis_gather_data_limits_result

- name: Gather data to ensure core dumps are restricted - sysctl
  command: /usr/sbin/sysctl fs.suid_dumpable
  become: yes
  changed_when: false
  register: cis_gather_data_sysctl_result

- name: Gather data to ensure core dumps are restricted - sysctl.conf
  command: >-
    /usr/bin/grep 'hard core' /etc/security/limits.conf /etc/security/limits.d/*
  become: yes
  changed_when: false
  register: cis_gather_data_sysctl_conf_result

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_limits_result.stdout | length == 0
      - cis_gather_data_sysctl_result.stdout == 'fs.suid_dumpable = 0'
      - cis_gather_data_sysctl_conf_result.stdout == 'fs.suid_dumpable = 0'
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
