---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: Ensure X Window System is not installed

- name: "{{ cis_check_description }}"
  vars:
    x11_installed_packages: >-
      {{ ansible_facts.packages.keys()
         | reject("search", "xorg-x11-font.*")
         | select("search", "xorg-x11-.*")
         | list }}
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - x11_installed_packages | length == 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
