---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure filesystem integrity is regularly checked

- name: Gather data to ensure filesystem integrity checks - /bin/crontab
  command: >-
    /bin/crontab -u root -l
  become: yes
  changed_when: no
  failed_when: no
  register: cis_gather_data_bin_crontab_result

- name: Gather data to ensure filesystem integrity checks - /etc/cron*
  command: >-
    /usr/bin/grep -r aide /etc/cron.* /etc/crontab
  become: yes
  changed_when: no
  failed_when: no
  register: cis_gather_data_etc_cron_result

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      'aide' in cis_gather_data_bin_crontab_result.stdout
      or cis_gather_data_etc_cron_result.stdout | length > 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
