---
- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure permissions on all logfiles are configured

- name: Gather data to to ensure permissions on all logfiles are configured
  become: yes
  find:
    paths: /var/log/
    file_type: file
    recurse: yes
  register: cis_log_files_result

- name: "{{ cis_check_description }}"
  vars:
    etc_passwd_lines: "{{ cis_etc_passwd_result['content'] | b64decode }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    # g-wx,o-rwx
    that: cis_log_files_result.files is all_at_least_restrictive_as("0740")
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
