---

- ansible.builtin.include_tasks: ../common/check_separate_partition.yml
  vars:
    check_partition_directory: /tmp
  name: "Perform check {{ cis_audit_item }} / {{ check_partition_directory }}"
  no_log: "{{ cis_no_log }}"
