---

- include_tasks: ../common/check_sshd.yml
  vars:
    description: Ensure SSH IgnoreRhosts is enabled
    value: ignorerhosts yes
  name: "Perform sshd config contains: {{ value }}"
  no_log: "{{ cis_no_log }}"
