---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure SSH IgnoreRhosts is enabled

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: '"ignorerhosts yes" in cis_sshd_config'
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
