---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure secure ICMP redirects are not accepted

- name: Ensure secure ICMP redirects are not accepted
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - ("net.ipv4.conf.all.secure_redirects = 0" in cis_kernel_params)
      - ("net.ipv4.conf.default.secure_redirects = 0" in cis_kernel_params)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
