---

- include_tasks: ../common/check_sshd.yml
  vars:
    description: Ensure SSH root login is disabled
    value: permitrootlogin no
  name: "Perform sshd config contains: {{ value }}"
  no_log: "{{ cis_no_log }}"
