---

- include_tasks: ../common/check_installed_package.yml
  vars:
    package: prelink
    present: no
    description: Ensure prelink is disabled
  name: >-
    Perform check {{ cis_audit_item }} / {{ description }}
  no_log: "{{ cis_no_log }}"
