---

- ansible.builtin.include_tasks: ../common/check_sshd.yml
  vars:
    description: Ensure SSH LogLevel is set to INFO
    value: loglevel INFO
  name: "Perform sshd config contains: {{ value }}"
  no_log: "{{ cis_no_log }}"
