---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: >-
      Ensure address space layout randomization (ASLR) is enabled

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: '"kernel.randomize_va_space = 2" in cis_kernel_params'
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
