---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: Ensure system accounts are non-login

- name: Gather data to to ensure system accounts are non-login
  ansible.builtin.slurp:
    src: /etc/passwd
  register: cis_etc_passwd_result

- name: "{{ cis_check_description }}"
  vars:
    etc_passwd_lines: "{{ cis_etc_passwd_result['content'] | b64decode }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      etc_passwd_lines
      is cis_user_system_not_login(cis_users_allowed_interactive_shell)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
