---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure session initiation information is collected

- name: Gather data from audit.rules and /etc/audit/rules.d/*.rules
  shell: >-
    grep --no-filename session
    /etc/audit/audit.rules /etc/audit/rules.d/*.rules ;
    grep --no-filename logins
    /etc/audit/audit.rules /etc/audit/rules.d/*.rule
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_audit_rules_result

- name: Gather data from auditctl
  shell: >-
    set -o pipefail ;
    auditctl -l | grep session ;
    auditctl -l | grep logins
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_auditctl_result

- name: "{{ cis_check_description }}"
  vars:
    desired_output:
      - "-w /var/run/utmp -p wa -k session"
      - "-w /var/log/wtmp -p wa -k logins"
      - "-w /var/log/btmp -p wa -k logins"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_audit_rules_result.stdout | length > 0
      - cis_gather_data_auditctl_result.stdout | length > 0
      - >-
        desired_output
        is subset(cis_gather_data_audit_rules_result.stdout_lines)
      - >-
        desired_output
        is subset(cis_gather_data_auditctl_result.stdout_lines)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
