---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure SSH MaxAuthTries is set to 4 or less

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: maxauthtries_value | int <= 4
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
  vars:
    maxauthtries_value: >-
      {{ cis_sshd_config
         | select("search", "maxauthtries")
         | list
         | first
         | regex_replace("maxauthtries (.*)", "\1") }}
