---

- ansible.builtin.include_tasks: ../common/check_param.yml
  vars:
    description: >-
      Ensure system is disabled when audit logs are full (space_left_action)
    file: /etc/audit/auditd.conf
    separator: " = "
    parameter: space_left_action
    lower_current_value: yes
    value: email
    value_type: string
    comparison: "=="
  name: "Check {{ parameter }}{{ comparison }}{{ value }} in {{ file }}"
  no_log: "{{ cis_no_log }}"

- name: Setup fact with partial check result
  ansible.builtin.set_fact:
    cis_partial_check_result_1: "{{ cis_check_result }}"

- ansible.builtin.include_tasks: ../common/check_param.yml
  vars:
    description: >-
      Ensure system is disabled when audit logs are full (action_mail_acct)
    file: /etc/audit/auditd.conf
    separator: " = "
    parameter: action_mail_acct
    lower_current_value: yes
    value: root
    value_type: string
    comparison: "=="
  name: "Check {{ parameter }}{{ comparison }}{{ value }} in {{ file }}"
  no_log: "{{ cis_no_log }}"

- name: Setup fact with partial check result
  ansible.builtin.set_fact:
    cis_partial_check_result_2: "{{ cis_check_result }}"

- ansible.builtin.include_tasks: ../common/check_param.yml
  vars:
    description: >-
      Ensure system is disabled when audit logs are full
      (admin_space_left_action)
    file: /etc/audit/auditd.conf
    separator: " = "
    parameter: admin_space_left_action
    lower_current_value: yes
    value: halt
    value_type: string
    comparison: "=="
  name: "Check {{ parameter }}{{ comparison }}{{ value }} in {{ file }}"
  no_log: "{{ cis_no_log }}"

- name: Setup fact with partial check result
  ansible.builtin.set_fact:
    cis_partial_check_result_3: "{{ cis_check_result }}"

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: Ensure system is disabled when audit logs are full

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_partial_check_result_1 is success
      - cis_partial_check_result_2 is success
      - cis_partial_check_result_3 is success
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
