---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure kernel module loading and unloading is collected

- name: Gather data from audit.rules and /etc/audit/rules.d/*.rules
  shell: >-
    grep --no-filename modules
    /etc/audit/audit.rules /etc/audit/rules.d/*.rules
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_audit_rules_result

- name: Gather data from auditctl
  shell: auditctl -l | grep modules
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_auditctl_result

- name: "{{ cis_check_description }}"
  vars:
    desired_output_32:
      - "-w /sbin/insmod -p x -k modules"
      - "-w /sbin/rmmod -p x -k modules"
      - "-w /sbin/modprobe -p x -k modules"
      - "-a always,exit -F arch=b32 -S init_module -S delete_module -k modules"

    desired_output_64:
      - "-w /sbin/insmod -p x -k modules"
      - "-w /sbin/rmmod -p x -k modules"
      - "-w /sbin/modprobe -p x -k modules"
      - "-a always,exit -F arch=b64 -S init_module -S delete_module -k modules"

    desired_output: >-
      {{ (ansible_facts.architecture == "x86_64")
         | ternary(desired_output_64, desired_output_32) }}
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_audit_rules_result.stdout | length > 0
      - cis_gather_data_auditctl_result.stdout | length > 0
      - >-
        desired_output
        is subset(cis_gather_data_audit_rules_result.stdout_lines)
      - >-
        desired_output
        is subset(cis_gather_data_auditctl_result.stdout_lines)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
