---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: >-
      Ensure default user shell timeout is 900 seconds or less

- name: Gather TMOUT from /etc/profile and /etc/bashrc
  ansible.builtin.shell: |-
    /usr/bin/grep "^TMOUT" /etc/profile /etc/profile.d/* /etc/bashrc
  changed_when: no
  failed_when: no
  register: cis_gather_data_tmout_result

- name: "{{ cis_check_description }}"
  vars:
    tmout: >-
      {{ cis_gather_data_tmout_result.stdout | cis_script_variable_value }}
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - "tmout | length > 0"
      - "tmout | int <= 900"
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
