---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure core dumps are restricted

- name: Gather data to ensure core dumps are restricted - limits
  shell: >-
    set -o pipefail # Raise internal pipe errors
    /usr/bin/grep -E
    '^[^#].*\*.*hard|-.*core.*0'
    /etc/security/limits.conf
    /etc/security/limits.d/*
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_limits_result

- name: Gather data to ensure core dumps are restricted - sysctl
  command: /usr/sbin/sysctl fs.suid_dumpable
  changed_when: false
  register: cis_gather_data_sysctl_result

- name: Gather data to ensure core dumps are restricted - sysctl.conf
  shell: >-
    grep --no-filename
    "fs\.suid_dumpable *= *0"
    /etc/sysctl.conf
    /etc/sysctl.d/*
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_sysctl_conf_result

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_limits_result.stdout | length > 0
      - cis_gather_data_sysctl_result.stdout == 'fs.suid_dumpable = 0'
      - cis_gather_data_sysctl_conf_result.stdout_lines | length > 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
