---

- name: Ensure SSH X11 forwarding is disabled
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: '"x11forwarding no" in cis_sshd_config'
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
