---

- ansible.builtin.include_tasks: ../common/check_kernel_module.yml
  vars:
    check_filesystem_type: jffs2
  name: "Perform kernel module {{ check_filesystem_type }} check"
  no_log: "{{ cis_no_log }}"
