---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure X Window System is not installed

- name: "{{ cis_check_description }}"
  vars:
    x11_installed_packages: >-
      {{ ansible_facts
      | json_query('packages.keys(@)[?starts_with(@, `xorg-x11-`) == `true`]')
      | list }}
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - x11_installed_packages | length == 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
