---

- include_tasks: ../common/check_net_kernel_params.yml
  vars:
    description: Ensure Reverse Path Filtering is enabled
    protocol: ipv4
    param_name: rp_filter
    desired_value: 1
  name: "Perform {{ param_name }} {{ protocol }} netwok kernel module check"
  no_log: "{{ cis_no_log }}"
