---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure SSH LogLevel is set to INFO

- name: Ensure SSH LogLevel is set to INFO
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: '"loglevel INFO" in cis_sshd_config'
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
