---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure SSH root login is disabled

- name: Gather data to to ensure SSH root login is disabled
  become: yes
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin\s+no'
    state: absent
  check_mode: yes
  changed_when: no
  register: cis_ssh_root_disabled_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: cis_ssh_root_disabled_result.found
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
