---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: Ensure bootloader password is set

- name: Read /boot/grub2/grub.cfg
  ansible.builtin.command: /usr/bin/cat /boot/grub2/grub.cfg
  changed_when: no
  register: cis_read_boot_grub2_grub_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      cis_read_boot_grub2_grub_result.stdout_lines
      | select("search", "^GRUB2_PASSWORD")
      | list
      | length != 0
  no_log: "{{ cis_no_log }}"
