---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure separate partition exists for /home

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - ansible_facts | json_query("mounts[?mount=='/home'].mount") | length > 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
