---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure default deny firewall policy

- name: Gather data to to ensure default deny firewall policy
  become: yes
  command: >-
    /sbin/iptables -L
  changed_when: no
  register: cis_firewall_deny_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - "'Chain INPUT (policy DROP)' in cis_firewall_deny_result.stdout_lines"
      - "'Chain FORWARD (policy DROP)' in cis_firewall_deny_result.stdout_lines"
      - "'Chain OUTPUT (policy DROP)' in cis_firewall_deny_result.stdout_lines"
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
