- name: Gather data to ensure ntp is configured - ntp.conf - restrict
  command: /usr/bin/grep "^restrict" /etc/ntp.conf
  become: yes
  changed_when: false
  register: cis_gather_data_restrict_result

- name: Gather data to ensure ntp is configured - ntp.conf - server_pool
  command: /usr/bin/egrep "^(server|pool)" /etc/ntp.conf
  become: yes
  changed_when: false
  register: cis_gather_data_server_pool_result

- name: Gather data to ensure ntp is configured - sysconfig/ntpd - options
  command: /usr/bin/grep "^OPTIONS" /etc/sysconfig/ntpd
  become: yes
  changed_when: false
  register: cis_gather_data_options_result

- name: Gather data to ensure ntp is configured - ntpd.service - execstart
  command: /usr/bin/grep "^ExecStart" /usr/lib/systemd/system/ntpd.service
  become: yes
  changed_when: false
  register: cis_gather_data_execstart_result

- name: Ensure core dumps are restricted
  assert:
    that:
      - ('-6' in cis_gather_data_restrict_result.stdout)
      - ('kod' in cis_gather_data_restrict_result.stdout)
      - ('nomodify' in cis_gather_data_restrict_result.stdout)
      - ('notrap' in cis_gather_data_restrict_result.stdout)
      - ('nopeer' in cis_gather_data_restrict_result.stdout)
      - ('noquery' in cis_gather_data_restrict_result.stdout)
      # FIXME: Not enough to check:
      #      # grep "^restrict" /etc/ntp.conf
      #     restrict -4 default kod nomodify notrap nopeer noquery
      #     restrict -6 default kod nomodify notrap nopeer noquery
      #     The -4 in the first line is optional and options after default can appear in any order. Additional restriction lines may exist. Run the following command and verify remote server is configured properly:
      - (cis_gather_data_server_pool_result | length > 0)
      # TODO: check desired ntp in cis_gather_data_server_pool_result
      - (' -u ntp:ntp ' in cis_gather_data_options_result.stdout or ' -u ntp:ntp ' in cis_gather_data_execstart_result.stdout)
  register: cis_check_result
