---

- name: Test to ensure X Window System is not installed
  yum:
    name: xorg-x11*
    state: absent
  register: x_check_result
  check_mode: yes

- name: result
  debug:
    var: x_check_result

- name: Ensure X Window System is not installed
  assert:
    that:
      - x_check_result is not changed
      - x_check_result is success
  register: cis_check_result
