---

- ansible.builtin.include_tasks: ../common/check_grep.yml
  vars:
    description: >-
      Ensure rsyslog is configured to send logs to a remote log host
    pattern: "{{ cis_users_rsyslog_remote_log_pattern }}"
    files: "/etc/rsyslog.conf /etc/rsyslog.d/*.conf"
  name: >-
    Perform egrep {{ pattern }} in {{ files }}
  no_log: "{{ cis_no_log }}"
