---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: >-
      Ensure events that modify user/group information are collected

- name: Gather data from audit.rules and /etc/audit/rules.d/*.rules
  ansible.builtin.shell: >-
    grep --no-filename identity
    /etc/audit/audit.rules /etc/audit/rules.d/*.rules
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_audit_rules_result

- name: Gather data from auditctl
  ansible.builtin.shell: set -o pipefail ; auditctl -l | grep identity
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_auditctl_result

- name: "{{ cis_check_description }}"
  vars:
    desired_output:
      - "-w /etc/group -p wa -k identity"
      - "-w /etc/passwd -p wa -k identity"
      - "-w /etc/gshadow -p wa -k identity"
      - "-w /etc/shadow -p wa -k identity"
      - "-w /etc/security/opasswd -p wa -k identity"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_audit_rules_result.stdout | length > 0
      - cis_gather_data_auditctl_result.stdout | length > 0
      - >-
        desired_output
        is subset(cis_gather_data_audit_rules_result.stdout_lines)
      - >-
        desired_output
        is subset(cis_gather_data_auditctl_result.stdout_lines)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
