---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure rsyslog default file permissions configured

- name: Gather data to ensure rsyslog default file permissions configured
  command: >-
    grep "^\$FileCreateMode" /etc/rsyslog.conf /etc/rsyslog.d/*.conf
  changed_when: no
  failed_when: no
  register: cis_gather_rsyslog_perms_result

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      cis_gather_rsyslog_perms_result.stdout_lines is cis_good_rsyslog_perms

  register: cis_check_result
  no_log: "{{ cis_no_log }}"
