---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: Ensure the SELinux state is enforcing

- name: Gather data to ensure SELinux state is enforcing
  ansible.builtin.command: >-
    /usr/bin/grep "SELINUX=enforcing" /etc/selinux/config
  changed_when: no
  failed_when: no
  register: cis_gather_data_selinux_config_result

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - "'enforcing' == ansible_facts.selinux.config_mode"
      - "'enforcing' == ansible_facts.selinux.mode"
      - "'enabled' == ansible_facts.selinux.status"
      - "cis_gather_data_selinux_config_result.stdout | length > 0"
      - "'SELINUX=enforcing' in cis_gather_data_selinux_config_result.stdout"
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
