---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure login and logout events are collected

- name: Gather data from audit.rules and /etc/audit/rules.d/*.rules
  shell: >-
    grep --no-filename logins
    /etc/audit/audit.rules /etc/audit/rules.d/*.rules
  args:
    warn: no
  changed_when: no
  failed_when: no
  register: cis_gather_data_audit_rules_result

- name: "{{ cis_check_description }}"
  vars:
    desired_output:
      - "-w /var/log/lastlog -p wa -k logins"
      - "-w /var/run/faillock/ -p wa -k logins"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - cis_gather_data_audit_rules_result.stdout | length > 0
      - >-
        desired_output
        is subset(cis_gather_data_audit_rules_result.stdout_lines)
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
