---

- include_tasks: ../common/check_installed_package.yml
  vars:
    package: aide
    present: yes
    description: Ensure AIDE is installed
  name: >-
    Perform check {{ cis_audit_item }} / {{ description }}
  no_log: "{{ cis_no_log }}"
