---

- name: Setup fact with check description
  set_fact:
    cis_check_description: Ensure no unconfined daemons exist

- name: Gather data to ensure no unconfined daemons exist
  shell: |-
    set -o pipefail ;
    ps -eZ \
    | egrep "initrc" \
    | egrep -vw "tr|ps|egrep|bash|awk" \
    | tr ':' ' ' \
    | awk '{ print $NF }'
  changed_when: no
  failed_when: no
  register: cis_gather_data_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: cis_gather_data_result.stdout | length == 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
