---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure sticky bit is set on all world-writable directories

- name: Gather data to ensure sticky bit on all world-writeable directories
  shell: |-
    set -o pipefail # Raise internal pipe errors
    df --local -P \
    | awk {'if (NR!=1) print $6'} \
    | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \)
  become: yes
  changed_when: false
  register: cis_gather_data_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: cis_gather_data_result.stdout | length == 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
