---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure permissions on /etc/cron.monthly are configured

- name: Read permissions of /etc/cron.monthly
  stat:
    path: /etc/cron.monthly
  register: cis_stat_etc_cron_monthly_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      not cis_stat_etc_cron_monthly_result.stat.exists
      or (cis_stat_etc_cron_monthly_result.stat.pw_name == "root"
          and cis_stat_etc_cron_monthly_result.stat.gr_name == "root"
          and cis_stat_etc_cron_monthly_result.stat.mode == "0700")
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
