---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: >-
      Ensure permissions on bootloader config are configured

- name: Read permissions of /boot/grub2/grub.cfg
  ansible.builtin.stat:
    path: /boot/grub2/grub.cfg
  register: cis_stat_boot_grub2_grub_result
  no_log: "{{ cis_no_log }}"

- name: Read permissions of /boot/grub2/user.cfg
  ansible.builtin.stat:
    path: /boot/grub2/user.cfg
  register: cis_stat_boot_grub2_user_result
  no_log: "{{ cis_no_log }}"

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - >-
        not cis_stat_boot_grub2_grub_result.stat.exists
        or (cis_stat_boot_grub2_grub_result.stat.pw_name == "root"
            and cis_stat_boot_grub2_grub_result.stat.gr_name == "root"
            and cis_stat_boot_grub2_grub_result.stat.mode == "0700")
      - >-
        not cis_stat_boot_grub2_user_result.stat.exists
        or (cis_stat_boot_grub2_user_result.stat.pw_name == "root"
            and cis_stat_boot_grub2_user_result.stat.gr_name == "root"
            and cis_stat_boot_grub2_user_result.stat.mode == "0700")
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
