---

- name: Setup fact with check description
  ansible.builtin.set_fact:
    cis_check_description: Ensure xinetd is not enabled

- name: "{{ cis_check_description }}"
  ansible.builtin.assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      ansible_facts.services.keys()
      | map('regex_search', service_name)
      | difference([None])
      | length == 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
  vars:
    service_name: xinetd
