---


- name: Perform cis check
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/sbin:/sbin"
    # Ensure default english language
    LANGUAGE: en_US
  block:
    - name: Setup fact with supported audit checks
      ansible.builtin.set_fact:
        cis_supported_audit_checks_fact: "{{ cis_supported_audit_checks }}"

    - name: Gather kernel parameters
      ansible.builtin.command: "{{ cis_sysctl_ansible.builtin.command }} -a"
      changed_when: no
      register: cis_sysctl_result
      vars:
        cis_sysctl_command: >-
          {{ (ansible_facts.distribution_major_version is version("7", ">="))
             | ternary("/usr/sbin/sysctl", "/sbin/sysctl") }}

    - name: Setup fact with kernel parameters
      ansible.builtin.set_fact:
        cis_kernel_params: "{{ cis_sysctl_result.stdout_lines }}"

    - name: Gather kernel modules
      vars:
        cis_lsmod_command: >-
          {{ (ansible_facts.distribution_major_version is version("7", ">="))
          | ternary("/usr/sbin/lsmod", "/sbin/lsmod") }}
      ansible.builtin.command: "{{ cis_lsmod_command }}"
      changed_when: no
      register: cis_lsmod_result

    - name: Setup fact with kernel modules
      ansible.builtin.set_fact:
        cis_kernel_modules: "{{ cis_lsmod_result.stdout_lines }}"

    - name: Gather sshd configuration
      ansible.builtin.command: /usr/sbin/sshd -T
      changed_when: no
      register: cis_sshd_config_result

    - name: Setup fact with sshd configuration
      ansible.builtin.set_fact:
        cis_sshd_config: "{{ cis_sshd_config_result.stdout_lines }}"

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Run audit tasks   # noqa ignore-errors
      block:
        - ansible.builtin.include_tasks: run_check.yml
          loop: "{{ cis_audit | sort }}"
          loop_control:
            loop_var: cis_audit_item
            label: "CIS audit {{ cis_audit_item }}"
      ignore_errors: "{{ not cis_fail_at_non_fulfilment }}"
  tags:
    - role::cis
