---
# Role tasks

- environment:
      PATH: "{{ ansible_env.PATH }}:/usr/sbin:/sbin"
  block:
    - name: Setup fact with supported audit checks
      set_fact:
        cis_supported_audit_checks_fact: "{{ cis_supported_audit_checks }}"

    - name: Gather kernel parameters
      command: "{{ cis_sysctl_command }} -a"
      changed_when: no
      register: cis_sysctl_result
      vars:
        cis_sysctl_command: >-
          {{ (ansible_facts.distribution_major_version is version("7", ">="))
             | ternary("/usr/sbin/sysctl", "/sbin/sysctl") }}

    - name: Setup fact with kernel parameters
      set_fact:
        cis_kernel_params: "{{ cis_sysctl_result.stdout_lines }}"

    - name: Gather sshd configuration
      command: /usr/sbin/sshd -T
      changed_when: no
      register: cis_sshd_config_result

    - name: Setup fact with sshd configuration
      set_fact:
        cis_sshd_config: "{{ cis_sshd_config_result.stdout_lines }}"

    - block:
        - name: Run audit tasks
          include_tasks: run_check.yml
          loop: "{{ cis_audit | sort }}"
          loop_control:
            loop_var: cis_audit_item
            label: "CIS audit {{ cis_audit_item }}"
      ignore_errors: "{{ not cis_fail_at_non_fulfilment }}"
  tags:
    - role::cis
