---
# Role tasks

- ansible.builtin.include_tasks: >-
    audit/check_{{ cis_audit_item | regex_replace('\.', '_' ) }}.yml

- name: Save audit task result
  ansible.builtin.set_fact:
    cis_results_fact: >-
      {{ cis_results_fact | default([]) + [result_dict] }}
  vars:
    result_dict:
      "name": "{{ cis_audit_item }}"
      "description": "{{ cis_check_description }}"
      "passed": >-
        {{ not cis_check_result | default({"failed": "yes"}) is failed }}
