---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          cis_fail_at_non_fulfilment: no
          cis_quiet_assertions: no
          cis_no_log: no
          cis_audit:
            - 1.1.1.1
            - 1.1.1.2
            - 1.1.1.3
            - 1.1.1.4
            - 1.1.1.5
            - 1.1.1.6
            - 1.1.1.7
            - 1.1.1.8
            - 1.1.2
            - 1.1.3
            - 1.1.4
            - 1.1.5
            - 1.1.6
            - 1.1.7
            - 1.1.8
            - 1.1.9
            - 1.1.10
            - 1.1.11
            - 1.1.12
            - 1.1.13
            - 1.1.14
            - 1.1.15
            - 1.1.16
            - 1.1.17
            - 1.1.21
            - 1.3.1
            - 1.3.2
            - 1.4.1
            - 1.4.2
            - 1.5.1
            - 1.5.3
            - 1.5.4
            - 1.6.1.2
            - 1.6.1.3
            - 1.6.1.6
            - 2.1.7
            - 2.2.1.2
            - 2.2.2
            - 2.3.4
            - 2.3.5
            - 3.1.2
            - 3.2.1
            - 3.2.2
            - 3.2.3
            - 3.2.4
            - 3.2.7
            - 3.3.2
            - 3.4.3
            - 3.6.2
            - 3.6.5
            - 4.1.16
            - 4.2.1.3
            - 4.2.1.4
            - 4.2.4
            - 5.1.2
            - 5.1.3
            - 5.1.4
            - 5.1.5
            - 5.1.6
            - 5.1.7
            - 5.2.2
            - 5.2.3
            - 5.2.4
            - 5.2.5
            - 5.2.6
            - 5.2.7
            - 5.2.8
            - 5.2.9
            - 5.2.10
            - 5.2.11
            - 5.2.12
            - 5.2.13
            - 5.2.14
            - 5.2.15
            - 5.3.2
            - 5.3.3
            - 5.4.1.4
            - 5.4.2
            - 5.4.4
            - 5.4.5
            - 6.2.1
verifier:
  name: ansible
