---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        cis_fail_at_non_fulfilment: no
        cis_quiet_assertions: no
        cis_no_log: no
    host_vars:
      centos7:
        cis_audit:
          - 1.1.1.1
          - 1.1.1.2
          - 1.1.1.3
          - 1.1.1.4
          - 1.1.1.5
          - 1.1.1.6
          - 1.1.1.7
          - 1.1.1.8
          - 1.1.2
          - 1.1.3
          - 1.1.4
          - 1.1.5
          - 1.1.6
          - 1.1.7
          - 1.1.8
          - 1.1.9
          - 1.1.10
          - 1.1.11
          - 1.1.12
          - 1.1.13
          - 1.1.14
          - 1.1.15
          - 1.1.16
          - 1.1.17
          - 1.1.21
          - 1.3.1
          - 1.3.2
          - 1.4.1
          - 1.4.2
          - 1.5.1
          - 1.5.3
          - 1.5.4
          - 1.6.1.2
          - 1.6.1.3
          - 1.6.1.6
          - 2.1.7
          - 2.2.1.2
          - 2.2.2
          - 2.3.4
          - 2.3.5
          - 3.1.2
          - 3.2.1
          - 3.2.2
          - 3.2.3
          - 3.6.2
          - 3.6.5
          - 4.1.16
          - 4.2.1.3
          - 4.2.1.4
          - 4.2.4
          - 5.1.2
          - 5.1.3
          - 5.1.4
          - 5.1.5
          - 5.1.6
          - 5.1.7
          - 5.2.2
          - 5.2.3
          - 5.2.4
          - 5.2.5
          - 5.2.6
          - 5.2.8
          - 5.2.13
          - 5.3.2
          - 5.4.2
          - 5.4.5
          - 6.2.1

verifier:
  name: testinfra
  lint:
    name: flake8
