---

- name: Prepare
  hosts: all
  become: yes
  tasks:
    - name: Setup packages
      ansible.builtin.package:
        name:
          - crontabs
          - openssh-server
          - "{{ grub }}"
      vars:
        grub: >-
          {{ (ansible_facts.distribution_major_version
              is version("7", "<") | ternary("grub", "grub2") )}}
