---

- name: Setup fact with check description
  set_fact:
    cis_check_description: "{{ description }}"

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: '"{{ value }}" in cis_sshd_config'
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
