---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure {{ check_mount_option }} option set on
      {{ check_mount_path }} partition

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - >-
        (check_mount_option
         in (ansible_facts
             | json_query("mounts[?mount=='" + check_mount_path + "'].options")
             | default('')
             | join('')))
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
