---

- name: Setup fact with check description
  set_fact:
    cis_check_description: "{{ description }}"

- name: "Gather {{ parameter }} from {{ file }}"
  command: /usr/bin/egrep "^\\s*{{ parameter }}\\s+" {{ file }}
  changed_when: no
  failed_when: no
  register: cis_gather_data_result

- name: "{{ cis_check_description }}"
  vars:
    separator: "{{ delimiter | default(' ') }}"
    current_value: >-
      {{ cis_gather_data_result.stdout
         | cis_script_variable_value(delimiter=separator | default("=")) }}
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - "current_value | length > 0"
      # HACK: Beware the double interpolation
      - "current_value | {{ value_type }} {{ comparison }} value"
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
