---

- name: Setup fact with check description
  set_fact:
    cis_check_description: >-
      Ensure {{ check_mount_option }} option set on
      {{ check_mount_path }} partition

- name: "{{ cis_check_description }}"
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that: >-
      ansible_facts.mounts
      | selectattr("mount", "equalto", check_mount_path)
      | list
      | length == 0
      or ansible_facts.mounts
         | selectattr("mount", "equalto", check_mount_path)
         | selectattr("options", "search", check_mount_option)
         | list
         | length > 0
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
