---

- name: Setup fact with check description
  set_fact:
    cis_check_description: "{{ description }}"

- name: "{{ cis_check_description }}"
  vars:
    # package: xxx
    # present: yes
    length_to_be_present: "{{ present | ternary(1, 0) }}"
    query: "packages.keys(@)[?@ == '{{ package }}']"
    package_is_installed: >-
      {{ ansible_facts
         | json_query(query)
         | length == (length_to_be_present | int) }}
  assert:
    quiet: "{{ cis_quiet_assertions }}"
    that:
      - package_is_installed | bool
  register: cis_check_result
  no_log: "{{ cis_no_log }}"
